<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_Grid</name>
   <tag></tag>
   <elementGuidId>812820be-558d-411e-8d1d-607311ec65f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-component-type='${component}']/div/div[${index}]//h2//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@data-component-type='${component}']/div/div[${index}]//h2//span</value>
   </webElementProperties>
</WebElementEntity>
